services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: AI-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}